name: ppo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - aiosignal=1.2.0
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.7.22
  - cachetools=4.2.2
  - certifi=2023.7.22
  - charset-normalizer=2.0.4
  - cpuonly=2.0
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.6.0
  - grpc-cpp=1.48.2
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=13.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - ncurses=6.4
  - nettle=3.7.3
  - numpy-base=1.25.2
  - openh264=2.1.1
  - openssl=3.0.10
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - python=3.11.4
  - pytorch=2.0.1
  - pytorch-mutex=1.0
  - re2=2022.04.01
  - readline=8.2
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tensorboard-plugin-wit=1.6.0
  - tk=8.6.12
  - typing_extensions=4.7.1
  - tzdata=2023c
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.3
    - async-timeout==4.0.2
    - attrs==22.1.0
    - blinker==1.4
    - box2d-py==2.3.8
    - brotlipy==0.7.0
    - cffi==1.15.1
    - click==8.0.4
    - cloudpickle==2.2.1
    - cryptography==41.0.2
    - farama-notifications==0.0.4
    - filelock==3.9.0
    - frozenlist==1.3.3
    - gmpy2==2.1.2
    - google-auth-oauthlib==0.5.2
    - grpcio==1.48.2
    - gymnasium==0.28.1
    - idna==3.4
    - jax-jumpy==1.0.0
    - jinja2==3.1.2
    - markdown==3.4.1
    - markupsafe==2.1.1
    - mkl-fft==1.3.6
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - mpmath==1.3.0
    - multidict==6.0.2
    - networkx==3.1
    - numpy==1.25.2
    - oauthlib==3.2.2
    - pillow==9.4.0
    - pip==23.2.1
    - protobuf==3.20.3
    - pygame==2.1.3
    - pyjwt==2.4.0
    - pyopenssl==23.2.0
    - pysocks==1.7.1
    - requests==2.31.0
    - setuptools==68.0.0
    - swig==4.1.1
    - sympy==1.11.1
    - tensorboard==2.12.1
    - tensorboard-data-server==0.7.0
    - torch==2.0.1
    - torchaudio==2.0.2
    - torchvision==0.15.2
    - tqdm==4.65.0
    - typing-extensions==4.7.1
    - urllib3==1.26.16
    - werkzeug==2.2.3
    - wheel==0.38.4
    - yarl==1.8.1
